//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Go.Windows {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Go.Windows.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unable to open configuration file.
        /// </summary>
        internal static string ConfigurationFileReadError {
            get {
                return ResourceManager.GetString("ConfigurationFileReadError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; file not found for &apos;{1}&apos; file..
        /// </summary>
        internal static string ConfigurationNotFoundFormat {
            get {
                return ResourceManager.GetString("ConfigurationNotFoundFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error: {0}.
        /// </summary>
        internal static string ErrorTextFormat {
            get {
                return ResourceManager.GetString("ErrorTextFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Exception {0}: {1}.
        /// </summary>
        internal static string ExceptionFormat {
            get {
                return ResourceManager.GetString("ExceptionFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ..with inner Exception {0}: {1}.
        /// </summary>
        internal static string InnerExceptionFormat {
            get {
                return ResourceManager.GetString("InnerExceptionFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Message: {0}.
        /// </summary>
        internal static string MessageTextFormat {
            get {
                return ResourceManager.GetString("MessageTextFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Contextool.
        /// </summary>
        internal static string OutputPaneName {
            get {
                return ResourceManager.GetString("OutputPaneName", resourceCulture);
            }
        }
    }
}
